services:
  celery-worker:
    build:
      context: .
      dockerfile: parser/Dockerfile
      target: main-stage
    command:
      - celery
      - -A
      - celery_conf.celery
      - worker
      - -l
      - info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./parser:/tz_parser/parser
  celery-beat:
    build:
      context: .
      dockerfile: parser/Dockerfile
      target: main-stage
    command:
      - celery
      - -A
      - celery_conf.celery
      - beat
      - -l
      - info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./parser:/tz_parser/parser
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=parser
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=nasternaka05@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=qekleqqe
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5555
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/:/data
volumes:
  redis_data: