services:
  celery-worker:
    build:
      context: .
      dockerfile: parser/Dockerfile
      target: main-stage
    command:
      - celery
      - -A
      - celery_config.celery
      - worker
      - -l
      - info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./parser:/tz_parser/parser
  celery-beat:
    build:
      context: .
      dockerfile: parser/Dockerfile
      target: main-stage
    command:
      - celery
      - -A
      - celery_config.celery
      - beat
      - -l
      - info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./parser:/tz_parser/parser
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/:/data
volumes:
  redis_data: